# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://t-kl.github.io/analysis/"

git_url = "https://github.com/t-kl/analysis/tree/master/"

def custom_doc_links(name): return None
